mapping = [
    ("basic_info.authorname", "\\authorname"),
    ("basic_info.authorname_en", "\\authornameen"),
    ("basic_info.student_number", "\\studentnumber"),
    ("basic_info.university", "\\univ"),
    ("basic_info.university_en", "\\univen"),
    ("basic_info.affiliation", "\\affiliation"),
    ("basic_info.affiliation_en", "\\affiliationen"),
    ("basic_info.department", "\\department"),
    ("basic_info.major", "\\major"),
    ("basic_info.course", "\\course"),
    ("title.main", "\\maintitle"),
    ("title.sub", "\\subtitle"),
    ("title.main_en", "\\maintitleen"),
    ("approval.supervisor", "\\supervisor"),
    ("approval.publish_year_month", "\\publishyearmonth"),
    ("approval.submit_year_month", "\\submityearmonth"),
    ("approval.committee.chair", "\\comchair"),
    ("approval.committee.vice_chair", "\\comvicechair"),
    ("approval.committee.member", "\\commember"),
    ("abstract.keyword", "\\abstractkeyword"),
    ("abstract.keyword_en", "\\abstractkeyworden"),
]
